return {
  "CopilotC-Nvim/CopilotChat.nvim",
  branch = "main",
  dependencies = {
    { "nvim-lua/plenary.nvim" },
    { "github/copilot.vim" }, -- or github/copilot.vim
  },
  opts = {
    debug = true, -- Enable debugging
    system = "Ты полезный помощник. Объясняй все на русском языке.",
    show_folds = false, -- Don't automatically fold the chat window
    question_icon = "?",
    answer_icon = "A",
    prompts = {
      Explain = "Объясни этот код.",
      Refactor = "Рефакторинг этого кода.",
      Tests = "Напиши тесты для этого кода.",
      Docs = "Напиши документацию для этого кода.",
      Review = "Проверь этот код на наличие ошибок и предложи улучшения.",
    },
    keybindings = {
      open = ",cc",
      quit = "q",
      submit = "<CR>",
      yank_last = ",cy",
      yank_last_code = ",cK",
      toggle_help = ",ch",
      toggle_settings = ",cs",
      cycle_windows = ",cw",
      next_response = ",cn",
      prev_response = ",cp",
      new_session = ",cN",
      reset_session = ",cr",
      cut_last_code = ",cx",
      copy_last_code = ",cC",
      insert_last_code = ",ci",
      insert_last_code_block = ",cB",
      insert_last_code_block_diff = ",cD",
      insert_last_code_block_diff_hunk = ",cH",
      insert_last_code_block_diff_hunk_reverse = ",cR",
      insert_last_code_block_diff_hunk_reverse_all = ",cA",
      insert_last_code_block_diff_hunk_reverse_all_force = ",cF",
      insert_last_code_block_diff_hunk_reverse_all_force_no_confirm = ",cZ",
      insert_last_code_block_diff_hunk_reverse_all_force_no_confirm_no_undo = ",cX",
      insert_last_code_block_diff_hunk_reverse_all_force_no_confirm_no_undo_no_save = ",cV",
      insert_last_code_block_diff_hunk_reverse_all_force_no_confirm_no_undo_no_save_no_quit = ",cB",
      insert_last_code_block_diff_hunk_reverse_all_force_no_confirm_no_undo_no_save_no_quit_no_close = ",cN",
      insert_last_code_block_diff_hunk_reverse_all_force_no_confirm_no_undo_no_save_no_quit_no_close_no_focus = ",cM",
      insert_last_code_block_diff_hunk_reverse_all_force_no_confirm_no_undo_no_save_no_quit_no_close_no_focus_no_scroll = ",cL",
      insert_last_code_block_diff_hunk_reverse_all_force_no_confirm_no_undo_no_save_no_quit_no_close_no_focus_no_scroll_no_cursor = ",cK",
      insert_last_code_block_diff_hunk_reverse_all_force_no_confirm_no_undo_no_save_no_quit_no_close_no_focus_no_scroll_no_cursor_no_highlight = ",cJ",
      insert_last_code_block_diff_hunk_reverse_all_force_no_confirm_no_undo_no_save_no_quit_no_close_no_focus_no_scroll_no_cursor_no_highlight_no_status = ",cH",
      insert_last_code_block_diff_hunk_reverse_all_force_no_confirm_no_undo_no_save_no_quit_no_close_no_focus_no_scroll_no_cursor_no_highlight_no_status_no_messages = ",cG",
      insert_last_code_block_diff_hunk_reverse_all_force_no_confirm_no_undo_no_save_no_quit_no_close_no_focus_no_scroll_no_cursor_no_highlight_no_status_no_messages_no_errors = ",cF",
      insert_last_code_block_diff_hunk_reverse_all_force_no_confirm_no_undo_no_save_no_quit_no_close_no_focus_no_scroll_no_cursor_no_highlight_no_status_no_messages_no_errors_no_warnings = ",cE",
      insert_last_code_block_diff_hunk_reverse_all_force_no_confirm_no_undo_no_save_no_quit_no_close_no_focus_no_scroll_no_cursor_no_highlight_no_status_no_messages_no_errors_no_warnings_no_info = ",cD",
      insert_last_code_block_diff_hunk_reverse_all_force_no_confirm_no_undo_no_save_no_quit_no_close_no_focus_no_scroll_no_cursor_no_highlight_no_status_no_messages_no_errors_no_warnings_no_info_no_debug = ",cC",
      insert_last_code_block_diff_hunk_reverse_all_force_no_confirm_no_undo_no_save_no_quit_no_close_no_focus_no_scroll_no_cursor_no_highlight_no_status_no_messages_no_errors_no_warnings_no_info_no_debug_no_trace = ",cB",
      insert_last_code_block_diff_hunk_reverse_all_force_no_confirm_no_undo_no_save_no_quit_no_close_no_focus_no_scroll_no_cursor_no_highlight_no_status_no_messages_no_errors_no_warnings_no_info_no_debug_no_trace_no_log = ",cA",
    },
  },
}
